### ISSUE TITLE
Webbrowser is emitting GTK warnings to the console

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/federated-aws-cli#102]
Under Ubuntu 18.04 the `webbrowser` python module is sending firefox browser warnings out to the console which is corrupting the environment variable exports.

```
(firefox:3208): Gtk-WARNING **: 08:39:19.008: Theme parsing error: gtk.css:8:12: Not using units is deprecated. Assuming 'px'.
```

I'd worked around this in the past but we reverted that workaround code here

https://github.com/mozilla-iam/federated-aws-cli/pull/68#issuecomment-524078083

We need to add something in to address this.

**Comment by april** [comment]
Want me to fire up a VM and work on this? It might be possible to make this work by fiddling around with `sys.stdout` and the like.

**Comment by gene1wood** [comment]
@april If the VM route is easy yes, if not, I can take care of this issue,.
