### ISSUE TITLE
Need to supress https://sso.mozilla.com/claim/groups

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/federated-aws-cli#62]
It looks like the https://sso.mozilla.com/claim/groups in the id token is causing the ID token to exceed the 2048 limit.

Can we set the groups claim to the same value as the `amr` claim in the Auth0 rule?

**Comment by gdestuynder** [comment]
> Can we set the groups claim to the same value as the amr claim in the Auth0 rule?

For the aws clients the claim can be dropped, or the scope request can be changed to only be `openid`

**Comment by gene1wood** [comment]
Ok, using only `openid` scope fixed the problem. To ensure that this client never gets the groups claim, how's best to overwrite that claim with the `amr` value (essentially, how does one modify the group claim contents in a rule)?

I looked at a few existing rules but wasn't clear on which steps caused the claim value to change

**Comment by gdestuynder** [comment]
the id token claim is changed by overriding the id token itself.  here's an example: https://github.com/mozilla-iam/auth0-deploy/blob/master/rules/CIS-Claims-fixups.js#L219

that said, i wouldnt do this. By openid spec, only requesting `openid` will not add the claim. this means, if this stopped working it would be a bug and the openid spec backs this up. See also https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

**Comment by gene1wood** [comment]
Ok, so best solution here is to just cause the client to request only `openid`. I'll do that, thank you.
